CREATE TABLE "Airport" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE NOT NULL,
  "name" varchar NOT NULL,
  "city" varchar,
  "country" varchar
);

CREATE TABLE "Terminal" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE NOT NULL,
  "name" varchar,
  "airport_id" int
);

CREATE TABLE "Boarding_Gate" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar NOT NULL,
  "terminal_id" int
);

CREATE TABLE "Aircraft" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE NOT NULL,
  "model" varchar,
  "capacity" int,
  "airline_id" int
);

CREATE TABLE "Flight" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE NOT NULL,
  "origin_id" int,
  "destination_id" int,
  "aircraft_id" int,
  "boarding_gate_id" int,
  "departure_time" datetime,
  "arrival_time" datetime,
  "status" varchar
);

CREATE TABLE "Employee" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_number" varchar UNIQUE NOT NULL,
  "first_name" varchar,
  "last_name" varchar,
  "position" varchar,
  "hire_date" date,
  "salary" decimal
);

CREATE TABLE "Crew_Assignment" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" int,
  "flight_id" int,
  "role" varchar
);

CREATE TABLE "Passenger" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_number" varchar UNIQUE NOT NULL,
  "first_name" varchar,
  "last_name" varchar,
  "nationality" varchar,
  "birth_date" date
);

CREATE TABLE "Ticket" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticket_number" varchar UNIQUE NOT NULL,
  "passenger_id" int,
  "flight_id" int,
  "seat_number" varchar,
  "price" decimal
);

CREATE TABLE "Luggage" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticket_id" int,
  "weight" decimal,
  "type" varchar
);

CREATE TABLE "Check_In" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "passenger_id" int,
  "flight_id" int,
  "checkin_time" datetime,
  "luggage_count" int
);

CREATE TABLE "Boarding_Pass" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticket_id" int,
  "gate_id" int,
  "boarding_time" datetime
);

CREATE TABLE "Security_Check" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "passenger_id" int,
  "flight_id" int,
  "check_time" datetime
);

CREATE TABLE "Immigration" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "passenger_id" int,
  "flight_id" int,
  "clearance_time" datetime
);

CREATE TABLE "Customs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "passenger_id" int,
  "luggage_id" int,
  "inspection_status" varchar
);

CREATE TABLE "Airline" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "code" varchar UNIQUE NOT NULL,
  "country" varchar
);

CREATE TABLE "Maintenance" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "aircraft_id" int,
  "maintenance_date" datetime,
  "description" varchar,
  "status" varchar
);

CREATE TABLE "Role" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "description" varchar
);

CREATE TABLE "Permission" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "description" varchar
);

CREATE TABLE "User" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "role_id" int
);

CREATE TABLE "Role_Permission" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" int,
  "permission_id" int
);

ALTER TABLE "Terminal" ADD FOREIGN KEY ("airport_id") REFERENCES "Airport" ("id");

ALTER TABLE "Boarding_Gate" ADD FOREIGN KEY ("terminal_id") REFERENCES "Terminal" ("id");

ALTER TABLE "Aircraft" ADD FOREIGN KEY ("airline_id") REFERENCES "Airline" ("id");

ALTER TABLE "Flight" ADD FOREIGN KEY ("origin_id") REFERENCES "Airport" ("id");

ALTER TABLE "Flight" ADD FOREIGN KEY ("destination_id") REFERENCES "Airport" ("id");

ALTER TABLE "Flight" ADD FOREIGN KEY ("aircraft_id") REFERENCES "Aircraft" ("id");

ALTER TABLE "Flight" ADD FOREIGN KEY ("boarding_gate_id") REFERENCES "Boarding_Gate" ("id");

ALTER TABLE "Crew_Assignment" ADD FOREIGN KEY ("employee_id") REFERENCES "Employee" ("id");

ALTER TABLE "Crew_Assignment" ADD FOREIGN KEY ("flight_id") REFERENCES "Flight" ("id");

ALTER TABLE "Ticket" ADD FOREIGN KEY ("passenger_id") REFERENCES "Passenger" ("id");

ALTER TABLE "Ticket" ADD FOREIGN KEY ("flight_id") REFERENCES "Flight" ("id");

ALTER TABLE "Luggage" ADD FOREIGN KEY ("ticket_id") REFERENCES "Ticket" ("id");

ALTER TABLE "Check_In" ADD FOREIGN KEY ("passenger_id") REFERENCES "Passenger" ("id");

ALTER TABLE "Check_In" ADD FOREIGN KEY ("flight_id") REFERENCES "Flight" ("id");

ALTER TABLE "Boarding_Pass" ADD FOREIGN KEY ("ticket_id") REFERENCES "Ticket" ("id");

ALTER TABLE "Boarding_Pass" ADD FOREIGN KEY ("gate_id") REFERENCES "Boarding_Gate" ("id");

ALTER TABLE "Security_Check" ADD FOREIGN KEY ("passenger_id") REFERENCES "Passenger" ("id");

ALTER TABLE "Security_Check" ADD FOREIGN KEY ("flight_id") REFERENCES "Flight" ("id");

ALTER TABLE "Immigration" ADD FOREIGN KEY ("passenger_id") REFERENCES "Passenger" ("id");

ALTER TABLE "Immigration" ADD FOREIGN KEY ("flight_id") REFERENCES "Flight" ("id");

ALTER TABLE "Customs" ADD FOREIGN KEY ("passenger_id") REFERENCES "Passenger" ("id");

ALTER TABLE "Customs" ADD FOREIGN KEY ("luggage_id") REFERENCES "Luggage" ("id");

ALTER TABLE "Maintenance" ADD FOREIGN KEY ("aircraft_id") REFERENCES "Aircraft" ("id");

ALTER TABLE "User" ADD FOREIGN KEY ("role_id") REFERENCES "Role" ("id");

ALTER TABLE "Role_Permission" ADD FOREIGN KEY ("role_id") REFERENCES "Role" ("id");

ALTER TABLE "Role_Permission" ADD FOREIGN KEY ("permission_id") REFERENCES "Permission" ("id");
